package fr.miage.syp.publication.data.exception

class NoChallengeException : Exception("No challenge found")